# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e66e33e134d9e2fea4959122a7d30ab81733434dfa731ff195df38aac9ec0ea08c854afc8719e9f0f5eda8e03c0fce65e2c4aae8cdf02ff996440f08acc9f7cb

test:
  secret_key_base: 5d56c53b811032847cafdcada1e4c55bb096a6c107e0a13bb5be2724ddcc279aebbcb1329df929897f44151a15926558c41a2ff142f2f23ab841d310410fbe39

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
